package com.shaffaf.shaffafservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ComplainCommentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplainCommentAllPropertiesEquals(ComplainComment expected, ComplainComment actual) {
        assertComplainCommentAutoGeneratedPropertiesEquals(expected, actual);
        assertComplainCommentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplainCommentAllUpdatablePropertiesEquals(ComplainComment expected, ComplainComment actual) {
        assertComplainCommentUpdatableFieldsEquals(expected, actual);
        assertComplainCommentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplainCommentAutoGeneratedPropertiesEquals(ComplainComment expected, ComplainComment actual) {
        assertThat(actual)
            .as("Verify ComplainComment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplainCommentUpdatableFieldsEquals(ComplainComment expected, ComplainComment actual) {
        assertThat(actual)
            .as("Verify ComplainComment relevant properties")
            .satisfies(a -> assertThat(a.getComment()).as("check comment").isEqualTo(expected.getComment()))
            .satisfies(a -> assertThat(a.getAddedBy()).as("check addedBy").isEqualTo(expected.getAddedBy()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getDeletedOn()).as("check deletedOn").isEqualTo(expected.getDeletedOn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplainCommentUpdatableRelationshipsEquals(ComplainComment expected, ComplainComment actual) {
        assertThat(actual)
            .as("Verify ComplainComment relationships")
            .satisfies(a -> assertThat(a.getComplain()).as("check complain").isEqualTo(expected.getComplain()));
    }
}
