package com.shaffaf.shaffafservice.domain;

import static com.shaffaf.shaffafservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProjectAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectAllPropertiesEquals(Project expected, Project actual) {
        assertProjectAutoGeneratedPropertiesEquals(expected, actual);
        assertProjectAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectAllUpdatablePropertiesEquals(Project expected, Project actual) {
        assertProjectUpdatableFieldsEquals(expected, actual);
        assertProjectUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectAutoGeneratedPropertiesEquals(Project expected, Project actual) {
        assertThat(actual)
            .as("Verify Project auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectUpdatableFieldsEquals(Project expected, Project actual) {
        assertThat(actual)
            .as("Verify Project relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a ->
                assertThat(a.getFeesPerUnitPerMonth())
                    .as("check feesPerUnitPerMonth")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFeesPerUnitPerMonth())
            )
            .satisfies(a -> assertThat(a.getUnionHeadName()).as("check unionHeadName").isEqualTo(expected.getUnionHeadName()))
            .satisfies(a ->
                assertThat(a.getUnionHeadMobileNumber()).as("check unionHeadMobileNumber").isEqualTo(expected.getUnionHeadMobileNumber())
            )
            .satisfies(a -> assertThat(a.getNumberOfUnits()).as("check numberOfUnits").isEqualTo(expected.getNumberOfUnits()))
            .satisfies(a -> assertThat(a.getConsentProvidedBy()).as("check consentProvidedBy").isEqualTo(expected.getConsentProvidedBy()))
            .satisfies(a -> assertThat(a.getConsentProvidedOn()).as("check consentProvidedOn").isEqualTo(expected.getConsentProvidedOn()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectUpdatableRelationshipsEquals(Project expected, Project actual) {
        assertThat(actual)
            .as("Verify Project relationships")
            .satisfies(a -> assertThat(a.getSeller()).as("check seller").isEqualTo(expected.getSeller()));
    }
}
